services:
  # 🔹 Сервис веб-приложения (FastAPI)
  web:
    build: .  # Собираем образ из Dockerfile в текущей директории
    container_name: fastapi_app  # Имя контейнера (удобно для отладки)
    ports:
      - "8000:8000"  # Пробрасываем порт: локальный 8000 → контейнерный 8000
    volumes:
      - .:/app  # Монтируем текущую директорию внутрь контейнера (live-обновление кода)
    env_file:
      - .env  # Подключаем переменные окружения
    depends_on:
      - db  # Говорим: не запускай web, пока не будет готов db

  # 🔹 Сервис базы данных PostgreSQL
  db:
    image: postgres:17  # Образ с PostgreSQL версии 17
    container_name: postgres_db
    restart: always  # Перезапуск при сбое или перезапуске Docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}       # Пользователь из .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Пароль
      POSTGRES_DB: ${POSTGRES_DB}           # Название базы данных
    ports:
      - ${HOST_DB_PORT}:5432  # Пробрасываем порт PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные между перезапусками

volumes:
  postgres_data:  # Определяем volume для PostgreSQL данных  зщыепкуы_вфефЖ  № Jghtltkztv мщдгьу lkz ЗщыепкуЫЙД lfyys[
